[2024-02-03T04:49:06.523+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: weather_api_dag.get_weather_data scheduled__2024-02-03T03:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
